/**************************************************************************************************
 *
 *	XCS Crowd Simulation Software
 *	Author: Scott Bevin
 *	Web: www.gameXcore.co.uk
 *	Email: scott@gameXcore.co.uk
 *	All code (c)2010 Scott Bevin, all rights reserved.
 *	
 *	This software is part of the disssertation work entitled "Real time crowd simulations incorporating individual
 *	agent personality models and group interactions" submitted to The University of Bolton by Scott Bevin in partial
 *	fulfilment of the requirements of The University of Bolton for the degree of Bachelor of Science in May 2010.
 *	
 **************************************************************************************************/

 /************************************************************************

 This file is part of "Real time crowd simulations incorporating individual agent personality models and group interactions".

 "Real time crowd simulations incorporating individual agent personality 
 models and group interactions" is free software: you can redistribute 
 it and/or modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation, either version 3 of the 
 License, or (at your option) any later version.

 "Real time crowd simulations incorporating individual agent personality models and group interactions" is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with "Real time crowd simulations incorporating individual agent personality models and group interactions".  
 If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

// All code (c)2010 Scott Bevin, all rights reserved.

#include "GameEntity.h"

#include "XSystemComponents/XOgre/OgreRenderer.h"
#include "XUtilities/Utilities.h"
#include "XEntityComponents/EntityComponent.h"

#include <fstream>
#include "XEntityComponents/EntityComponentFactory.h"

namespace XF
{
	GameEntity::GameEntity() : mInitialized(false), mShouldDie(false)
	{	
		
	}

	GameEntity::GameEntity(GameEntity &copy) : ComponentContainer(copy), PropertyContainer(copy)
 	{
		mShouldDie = false;
	}

	GameEntity::~GameEntity()
	{
		ClearEntity();
		Update(0); //chris, delete all components marked for killing 
	}

	void GameEntity::Update(double dT)
	{
		UpdateComponents(dT);
	}

	void GameEntity::HandleInput(double dT, XF::Input* input)
	{
		HandleInputComponents(dT, input);
	}

	bool GameEntity::OnHandleMessage( const XF::Message& message )
	{
		return MessageComponents(message);
	}

	void GameEntity::BuildAgentScript(std::string fileName)
	{
		std::fstream file;

		file.open(fileName.c_str(), std::ios_base::out);

		if(file.is_open())
		{
			file << "// Script file autogenerated\n\n";
			file << "// Properties\n";

			for(std::map<std::string, IProperty*>::iterator it = mProperties.begin();
				it != mProperties.end(); ++it)
			{
				std::string type = PropertySerializer::StringFromTypeID((PropertySerializer::PropertyTypeId)it->second->TypeID());
				std::string name = it->second->Name();
				std::string value = it->second->ToString();

				file << "property " << type << " " << name << " " << value << ";\n";
			}

			file << "\n\n// Components\n";

			for(int i = 0; i < (int)mComponents.size(); ++i)
			{
				EntityComponent* thisComp = mComponents[i];

				std::string type = thisComp->ComponentName();

				file << "component " << type << "\n";

				for(std::map<std::string, IProperty*>::iterator it2 = thisComp->Properties().begin();
					it2 != thisComp->Properties().end(); ++it2)
				{
					std::string type = PropertySerializer::StringFromTypeID((PropertySerializer::PropertyTypeId)it2->second->TypeID());
					std::string name = it2->second->Name();
					std::string value = it2->second->ToString();

					file << "   " << type << " " << name << " " << value << ",\n";
				}

				file << ";\n";
			}

			file.close();
		}
	}
	 
	void GameEntity::Initialize()
	{
		mInitialized = true;
		mShouldDie = false;
		InitializeComponents();
	}

	void GameEntity::ClearComponents()
	{
		for(int i = 0; i < (int)mComponents.size(); ++i)
		{
			EntityComponent* thisComp = mComponents[i];

			thisComp->Shutdown();// chris
			thisComp->Kill();
		}
	}

	void GameEntity::IntegrateEntity( GameEntity *ent )
	{
		for(int i = 0; i < (int)ent->mComponents.size(); ++i)
		{
			EntityComponent* thisComp = ent->mComponents[i];

			EntityComponent* newComp = EntityComponentFactory::CreateComponent(thisComp->ComponentName(), this);

			newComp->CopyPropertys(thisComp);

			AddComponent(newComp);
		}

		for(std::map<std::string, IProperty*>::const_iterator it = ent->mProperties.begin();
			it != ent->mProperties.end(); ++it)
		{
			IProperty* newProp = PropertySerializer::CreateProperty((PropertySerializer::PropertyTypeId)it->second->TypeID(), it->first, it->second->ToString());
			AddProperty(newProp);
		}
	}

	void GameEntity::CopyEntity( GameEntity *ent )
	{
		ClearEntity();
		//Update( 0 ) ;//chris added so that components marked for death are deleted
		IntegrateEntity(ent);
	}
}